name: r2w-backend-demo-ci/cd

on:
  release:
    types: [ created ]
  push:
    branches:
      - master
      - "*"
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3 # v3.1.0

      - name: Build with Gradle
        run: ./gradlew build

  run_info:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
           echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
           echo "The run id is: $GITHUB_RUN_ID"
           echo "The GitHub Actor's username is: $GITHUB_ACTOR"
           echo "GitHub SHA: $GITHUB_SHA"
  git_hub_parallel:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Dummy parallel run
        run: |
          echo "Git hub parallel run"

  deploy:
    runs-on: ubuntu-latest
    needs: run_info
    steps:
      - name: check out code
        run: echo The username is ${{ inputs.username }}